version: '3'
services:
  web_server:
    build:
      context: ./web_server/
    container_name: apache2
    volumes:
      - ./magento2:/var/www/html
      - ./web_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
    links:
      - database_server

  database_server:
    build:
      context: ./database_server/
      args:
        - mysql_password=dsg_pass
        - mysql_database=magento2
    container_name: mysql
    volumes: 
      - ./database_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./database_server/mysql.sh:/etc/mysql.sh
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8580:80"
    #links:
    #  - database_server 
    environment:
    #  - PMA_HOST=mysql
      - PMA_HOST=10.0.0.100
  #
  phpmyadmin-local:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-local
    ports:
      - "8180:80"
    #links:
    #  - database_server 
    environment:
      - PMA_HOST=mysql
      
