version: '3'
services:
  web_server:
    build:
      context: ./web_server/
    container_name: apache2
    volumes:
      # - appdata
      - ./magento2/vendor:/var/www/html/vendor
      - ./magento2/composer.lock:/var/www/html/composer.lock
      - ./magento2/app:/var/www/html/app
      - ./magento2/dev:/var/www/html/dev
      - ./magento2/lib:/var/www/html/lib
      - ./magento2/setup:/var/www/html/setup
      - ./magento2/composer.json:/var/www/html/composer.json
      - ./magento2/auth.json:/var/www/html/auth.json
      - ./magento2/var/import:/var/www/html/var/import
      # - ./magento2/.git:/var/www/html/.git
      - ./web_server/magento.config:/etc/apache2/sites-enabled/magento.config
      - ./web_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "80:80"
    # depends_on:
    #   - database_server
    # links:
    #   - database_server
    networks:
      - <project_name>-network

    

  # database_server:
  #   build:
  #     context: ./database_server/
  #     args:
  #       - mysql_password=dsg_pass
  #       - mysql_database=magento2
  #   container_name: mysql
  #   volumes: 
  #     - ./database_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
  #     - ./database_server/mysql.sh:/etc/mysql.sh
  #     - ./database_server/mysql-data:/var/lib/mysql
  #   ports:
  #     - "3306:3306"

  database_server:
    image: mariadb
    ports:
     - 3300:3306
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=magento
    volumes:
      - ./database_server/mysql-data:/var/lib/mysql
    networks:
      - <project_name>-network

  phpmyadmin-119:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-119
    ports:
      - "8181:80"
    #links:
    #  - database_server 
    environment:
    #  - PMA_HOST=mysql
      - PMA_HOST=10.0.0.105

  #for php myadmin
  phpmyadmin-local:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-local
    ports:
      - "8180:80"
    environment:
      - PMA_HOST=mysql
    networks:
      - <project_name>-network  
  #for Cache
  redis:
    image: redis
    container_name: redis
    ports:
     - 6379
    networks:
      - <project_name>-network

  #for Session
  redis-session:
    image: redis
    container_name: redis-session
    ports:
     - 6379
    networks:
      - <project_name>-network

  #for mail
  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - 1025:1025
  #     - 8025:8025
  #   networks:
  #     - <project_name>-network

  ## for background sync
  # bg-sync:
  #   image: cweagans/bg-sync
  #   volumes:
  #     - ./magento2:/source
  #   volumes_from:
  #     - appdata
  #   environment:
  #     - SYNC_DESTINATION=/var/www/html
  #     - SYNC_MAX_INOTIFY_WATCHES=40000
  #     - SYNC_VERBOSE=1
  #   privileged: true
  
  ## for background sync
  # appdata:
  #   image: tianon/true
  #   volumes:
  #     - ./magento:/var/www/magento

networks:
  <project_name>-network:
    driver: bridge


      
